version: "3.9"

services:
  frontend:
    build:
      context: ./React
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - tinku

  backend1:
    build:
      context: ./Express
      target: production
    env_file:
      - ./Express/.env
    volumes:
      - common-space:/app/data
    depends_on:
      - mongodb
    networks:
      - tinku

  backend2:
    build:
      context: ./Express
      target: production
    env_file:
      - ./Express/.env
    volumes:
      - common-space:/app/data
    depends_on:
      - mongodb
    networks:
      - tinku

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tinku

volumes:
  common-space:
  mongo-data:

networks:
  tinku:
    driver: bridge
