version: "3.9"

services:
  frontend:
    build:
      context: ./React
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
    networks:
      - rajan

  backend1:
    build:
      context: ./Express
      target: production
    env_file:
      - ./Express/.env
    volumes:
      - common-space:/app/data
    networks:
      - rajan
  
  backend2:
    build:
      context: ./Express
      target: production
    env_file:
      - ./Express/.env
    volumes:
      - common-space:/app/data
    networks:
      - rajan

volumes:
  common-space:

networks:
  rajan:
    driver: bridge
